version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - ..:/Utari
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000
      - 5001:5001 # Cloud Functions
      - 8085:8085
      - 8080:8080 # Cloud Firestore
      - 9000:9000
      - 9005:9005
      - 9099:9099 # Auth
      - 9199:9199