name: CI on PR
on: pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x # see package.json
      - run: npm ci
      - run: npm run build
      - run: npm run test
